### ISSUE TITLE
`drone-runner-kube` got deprecated

### ISSUE THREAD

**Issue by pat-s** [volker-raschek/drone-runner-charts#5]
https://github.com/drone/charts/tree/master/charts/drone-runner-kube

I also realized that injecting env vars in the kube runner is buggy: https://community.harness.io/t/drone-runner-docker-environment-cant-set-empty-strings/11927.

As a side note, Drone seems to "properly" maintain their charts again. 

A big thanks (again) for maintaining this fork for such a long time so far! ❤️

**Comment by pat-s** [comment]
After trying them out for a few days, I switched back to your charts :) 😅 

No idea how to properly configure the docker-runner chart for usage in k8s - apparently it should be the way forward but I didn't manage.

**Comment by volker-raschek** [comment]
Hi @pat-s  
thanks for the hint. I didn't know that they marked the drone-runner-cube as deprecated.

Well, I'm not entirely surprised. I've also noticed a few inconveniences in the last two years that surely should have been fixed sooner or later.

Now about the dind (docker-in-docker) image. I am not so much in the matter, but I am surprised that they rely on it although the support of docker was marked as deprecated by kubernetes. The question is, who runs two container-runtimes on one node to get dind running on newer kubernetes versions? 

Dedicated docker CI nodes don't make sense to me personally and don't scale. I think in the long run they will have to look for an alternative, especially since the development has fallen asleep due to the acquisition of drone by Harness.

I personally don't think the Woodpecker-CI fork created by the acquisition is a bad thing. Since you do not have to completely rebuild the entire CI projects. If you have already thought about it and have an alternative suggestion I am interested :)

**Comment by pat-s** [comment]
> Now about the dind (docker-in-docker) image. I am not so much in the matter, but I am surprised that they rely on it although the support of docker was marked as deprecated by kubernetes. The question is, who runs two container-runtimes on one node to get dind running on newer kubernetes versions?

I agree. Nobody knows why. This also applies to the kube-runner deprecation. But neither the changelog nor in other places there is real documentation or worthwhile information to be found.

> Dedicated docker CI nodes don't make sense to me personally and don't scale. I think in the long run they will have to look for an alternative, especially since the development has fallen asleep due to the acquisition of drone by Harness.

Somewhat, it seems they have picked it up again but without real features. In the last years, not much changed and it seems like they even struggle to provide basic maintenance.

> I personally don't think the Woodpecker-CI fork created by the acquisition is a bad thing. Since you do not have to completely rebuild the entire CI projects. If you have already thought about it and have an alternative suggestion I am interested :)

Oh it's a nice project, for sure! I've tried it but will wait until v1.0.0 as many changes are incoming. And transitioning now would require quite some work.
Not yet sure if I will move to WP or use the newly Gitea Actions concept coming in Gitea 1.19 (if you haven't heard of it yet -> https://github.com/go-gitea/gitea/pull/21937). 

Closing the issue but feel free to reply if there's something worth to be discussed :) And thanks again!
